services:
    App\Factory\AnswerFactory:
        decorates: 'app.factory.answer'
        arguments:
            $factory: '@App\Factory\AnswerFactory.inner'

    App\Factory\GameSessionFactory:
        decorates: 'app.factory.game_session'
        arguments:
            $factory: '@App\Factory\GameSessionFactory.inner'
            $playerFactory: '@app.factory.player'

    App\Factory\QuestionFactory:
        decorates: 'app.factory.question'
        arguments:
            $factory: '@App\Factory\QuestionFactory.inner'

    App\Factory\RoundFactory:
        decorates: 'app.factory.round'
        arguments:
            $factory: '@App\Factory\RoundFactory.inner'
