services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Installer\Checker\CommandDirectoryChecker:
        public: true
        arguments:
            - "@filesystem"

    App\Installer\Provider\DatabaseSetupCommandsProvider:
        public: true
        arguments:
            - "@doctrine"

    App\Installer\Provider\DatabaseSetupCommandsProviderInterface: '@App\Installer\Provider\DatabaseSetupCommandsProvider'

    App\Installer\Setup\LocaleSetup:
        $locale: '%locale%'
