sylius_resource:
    resources:
        app.answer:
            classes:
                model: App\Entity\Answer
                form: App\Form\Type\AnswerType
        app.celebrity:
            classes:
                model: App\Entity\Celebrity
                form: App\Form\Type\CelebrityType
        app.oauth_client:
            classes:
                model: App\Entity\OAuth\Client
        app.game_session:
            classes:
                model: App\Entity\GameSession
        app.player:
            classes:
                model: App\Entity\Player
        app.round:
            classes:
                model: App\Entity\Round
                form: App\Form\Type\RoundType
        app.theme:
            classes:
                model: App\Entity\Theme
                repository: App\Repository\ThemeRepository
                form: App\Form\Type\Theme\ThemeType
            translation:
                classes:
                    model: App\Entity\ThemeTranslation
    translation:
        locale_provider: App\Provider\TranslationLocaleProvider
