sylius_resource:
    resources:
        app.celebrity:
            classes:
                model: App\Entity\Celebrity
                form: App\Form\Type\CelebrityType
        app.oauth_client:
            classes:
                model: App\Entity\OAuth\Client
        app.theme:
            classes:
                model: App\Entity\Theme
