app_api_game_session_create:
    methods: [POST]
    path: /users/{username}/game_sessions
    defaults:
        _controller: app.controller.game_session:createAction
        _sylius:
            factory:
                method: createForCustomerWithChallengedCustomer
                arguments:
                    - "expr:notFoundOnNull(service('app.context.customer').getCustomer())"
                    - "expr:notFoundOnNull(service('sylius.repository.customer').findOneByUsername($username))"
            serialization_contexts: [Default, Detailed]
