app_api_answer:
    resource: "api/answer.yaml"

app_api_game_session:
    resource: "api/game_session.yaml"

app_api_round:
    resource: "api/round.yaml"

app_api_security:
    resource: "api/security.yaml"

app_api_theme:
    resource: "api/theme.yaml"
