app_frontend_homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'frontend/homepage/index.html.twig'

app_frontend_account:
    resource: "frontend/account.yaml"
    prefix: "mon-compte"

sylius_frontend_customer:
    resource: "frontend/customers.yaml"

app_frontend_game_session:
    resource: "frontend/game_session.yaml"

app_frontend_round:
    resource: "frontend/round.yaml"

sylius_frontend_security:
    resource: "frontend/security.yaml"

app_frontend_partial:
    resource: "frontend/partial.yaml"
    prefix: "/_partial"
