#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Composer)" "DeadOrAliveQuizz"
run_command "composer validate --strict"
