services:
      App\Behat\Page\Backend\Celebrity\CreatePage:
          parent: app.behat.page.backend.crud.create
          public: false
          arguments: ["app_backend_celebrity_create"]

      App\Behat\Page\Backend\Celebrity\IndexPage:
          parent: app.behat.page.backend.crud.index
          public: false
          arguments: ["app_backend_celebrity_index"]

      App\Behat\Page\Backend\Celebrity\UpdatePage:
          class: App\Behat\Page\Backend\Administrator\UpdatePage
          parent: app.behat.page.backend.crud.update
          public: false
          arguments: ["app_backend_celebrity_update"]
