sylius_grid:
    grids:
        app_backend_theme:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.theme.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments:
                            $localeCode: '%locale%'
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [translation.name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
